config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :users
  resources :bugs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bug.rb
class Bug < ApplicationRecord
    enum issue_type: [:issue, :enhancement, :feature]
    enum priority: [:low, :medium, :high]
    enum status: [:open, :closed, :monitor]

    validates :title, :description, presence: true

    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord

    validates :fname, :lname, :email, presence: true
    
    VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
    validates :email, length: {maximum: 105}, uniqueness: {case_sensitive: false}, format: {with: VALID_EMAIL_REGEX}
    validates :thumbnail, allow_blank: true, format: {with:%r{\.(gif|jpg|png)\Z}i,message: 'must be a URL for GIF, JPG or PNG image.'}

    has_many :bugs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController
  before_action :set_bug, :set_issue_types, :set_priorities, :set_statuses, only: [:show, :edit, :update, :destroy]

  # GET /bugs
  # GET /bugs.json
  def index
    @bugs = Bug.all
  end

  # GET /bugs/1
  # GET /bugs/1.json
  def show
  end

  # GET /bugs/new
  def new
    @bug = Bug.new
  end

  # GET /bugs/1/edit
  def edit
  end

  # POST /bugs
  # POST /bugs.json
  def create
    @bug = Bug.new(bug_params)
    user = User.find(bug_params[:user_id])
    @bug.build_user(:id => user.id)

    respond_to do |format|
      if @bug.save
        format.html { redirect_to @bug, notice: 'Bug was successfully created.' }
        format.json { render :show, status: :created, location: @bug }
      else
        format.html { render :new }
        format.json { render json: @bug.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bugs/1
  # PATCH/PUT /bugs/1.json
  def update
    respond_to do |format|
      if @bug.update(bug_params)
        format.html { redirect_to @bug, notice: 'Bug was successfully updated.' }
        format.json { render :show, status: :ok, location: @bug }
      else
        format.html { render :edit }
        format.json { render json: @bug.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bugs/1
  # DELETE /bugs/1.json
  def destroy
    @bug.destroy
    respond_to do |format|
      format.html { redirect_to bugs_url, notice: 'Bug was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bug
      @bug = Bug.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bug_params
      params.require(:bug).permit(:title, :description, :issue_type, :priority, :status, :user_id)
    end

    def set_statuses
      @statuses = Bug.statuses
    end

    def set_issue_types
      @issue_types = Bug.issue_types
    end
  
    def set_priorities
      @priorities = Bug.priorities
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        @bugs = Bug.last(3)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:lname, :fname, :email, :thumbnail)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bugs_helper.rb
module BugsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bugs/_form.html.erb
<%= form_with(model: bug, local: true) do |form| %>
  <% if bug.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bug.errors.count, "error") %> prohibited this bug from being saved:</h2>

      <ul>
      <% bug.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.select :user_id,
       options_for_select(User.all.collect {|u| ["#{u.lname}, #{u.fname}", u.id]}, 
       selected: (@bug.user ? @bug.user.id : User.first.id))%>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :bug_title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :bug_description %>
  </div>

  <div class="field">
    <%= form.label :issue_type %>
    <%= form.select :issue_type, Bug.issue_types.keys, selected: @bug.issue_type %>
  </div>

  <div class="field">
    <%= form.label :priority %>
    <%= form.select :priority, Bug.priorities.keys, selected: @bug.priority %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.select :status, Bug.statuses.keys, selected: @bug.status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bugs/edit.html.erb
<h1>Editing Bug</h1>

<%= render 'form', bug: @bug %>

<%= link_to 'Show', @bug %> |
<%= link_to 'Back', bugs_path %>

app/views/bugs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bugs</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Title</th>
      <th>Description</th>
      <th>Issue type</th>
      <th>Priority</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bugs.each do |bug| %>
      <tr>
        <td><%= "#{(bug.user.try(:lname))} #{(bug.user.try(:fname))}" || "N/A" %></td>
        <td><%= bug.title %></td>
        <td><%= bug.description %></td>
        <td><%= bug.issue_type %></td>
        <td><%= bug.priority %></td>
        <td><%= bug.status %></td>
        <td><%= link_to 'Show', bug %></td>
        <td><%= link_to 'Edit', edit_bug_path(bug) %></td>
        <td><%= link_to 'Destroy', bug, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bug', new_bug_path %>

app/views/bugs/new.html.erb
<h1>New Bug</h1>

<%= render 'form', bug: @bug %>

<%= link_to 'Back', bugs_path %>

app/views/bugs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @bug.title %>
</p>

<p>
  <strong>User:</strong>
  <%= "#{(@bug.user.try(:lname))} #{(@bug.user.try(:fname))}" || "N/A" %>
</p>

<p>
  <strong>Description:</strong>
  <%= @bug.description %>
</p>

<p>
  <strong>Issue type:</strong>
  <%= @bug.issue_type %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @bug.priority %>
</p>

<p>
  <strong>Status:</strong>
  <%= @bug.status %>
</p>

<%= link_to 'Edit', edit_bug_path(@bug) %> |
<%= link_to 'Back', bugs_path %>

app/views/home/index.html.erb
<div class="jumbotron">
    <div class="container">
        <h1 class="display-3">Hello, world!</h1>
        <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
        <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more »</a></p>
    </div>
</div>

<div class="container">
        <div class="row">
            <% @bugs.each do |bug| %>          
                <div class ="col-md-4">
                    <h2><%= bug.title%></h2>
                    <p><%=bug.description.truncate_words(30)%></p>
                    <p>
                        <%= link_to 'Full Report >', bug, class: "btn btn-default"%>
                    </p>
                </div>
            <% end %>
        </div>
    <hr>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Bug Overflow", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/bugs">Bugs <span class="sr-only">(current)</span></a></li>
        <li><a href="/users">Users</a></li>
      </ul>
      <form class="navbar-form navbar-right">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BugOverflow</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
      <div class= "container"> 
        <%= yield %>
      </div>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <strong><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</strong>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.label :fname , "First Name"%>
    <%= form.text_field :fname, id: :user_fname, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :lname, "Last Name" %>
    <%= form.text_field :lname, id: :user_lname, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :email, "Email" %>
    <%= form.text_field :email, id: :user_email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :thumbnail, "Profile Image" %>
    <%= form.file_field :thumbnail, id: :user_thumbnail, class: "form-control-file" %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
    <%= link_to 'Cancel', users_path, class: "btn btn-danger" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<% if !notice.blank? %>
    <p id="notice" class="alert alert-success"><%= notice %></p>
<% end %>

<h1>Users</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th class="col-md-3">First Name</th>
      <th class="col-md-3">Last Name</th>
      <th class="col-md-3">Email</th>
      <th class="col-md-3">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
      <tr>
        <td class="col-md-3"><%= user.fname %></td>
        <td class="col-md-3"><%= user.lname %></td>
        <td class="col-md-3"><%= user.email %></td>
        <td class="col-md-3">
          <%= link_to user, class: "btn btn-default btn-sm" do %>
          <i class="glyphicon glyphicon-eye-open"></i> Show
          <% end %>
          <%= link_to edit_user_path(user), class: "btn btn-default btn-sm" do %>
          <i class="glyphicon glyphicon-pencil"></i> Edit
          <% end %>
          <%= link_to user, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" do %>
          <i class="glyphicon glyphicon-trash"></i> Delete
          <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <br/>
  <%= link_to 'New User', new_user_path, :class => "btn btn-primary" %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<ul class="list-group">
  <li class="list-group-item">First Name: 
    <%=@user.fname%>
  </li>
  <li class="list-group-item">Last Name:
    <%=@user.lname%>
  </li>
  <li class="list-group-item">Emai:
    <%=@user.email%>
  </li>
  <li class="list-group-item">Thumbnail:
    <%=@user.thumbnail%>
  </li>
</ul>